### ISSUE TITLE
[REQ] Extending appops capabilities

### ISSUE THREAD

**Issue by pzrjcjgd** [AospExtended/platform_packages_apps_Settings#228]
I don't know if it's right place to suggest following, but anyway — is it possible to implement another appops permission called NETWORK in the way it is done in coperheados to avoid using firewall?

> The INTERNET permission is marked as dangerous to make it user-facing and added to a new NETWORK permission group with a user-facing toggle. Unlike other dangerous permissions, it’s enabled by default for apps targeting API level 23 or later for compatibility.
https://copperhead.co/android/docs/technical_overview#permissions

**Comment by theimpulson** [comment]
We are not adding any new features in old versions and have already moved to Privacy Guard on current one depreciating AppOps. Closing this down due to inactivity. Kindly contact on our Telegram group for future requests and faster replies.

Thank you.
